### ISSUE TITLE
Whitespace clarifications

### ISSUE THREAD

**Issue by mparadinha** [hqnna/mocha#5]
I have a few questions regarding whitespace that the spec does not cover:
1. what counts as whitespace? space (`0x20`), newline (`0x0a`), tab (`0x09`)? carriage return (`0x0d`)?
2. can there be whitespace between an identifier and the colon?
3. what about whitespace before/after the colon in references?
4. what whitespace is allowed inside a comment? I'm assuming it's all whitespace except newlines, which terminate the comment
5. how are tokens separated? I'm assuming any amount of whitespace could separate tokens

I'd be more than happy to make a PR to address these issues, if you could clarify them for me. :smile:

PS: I think this new file format is great! :heart:

**Comment by hqnna** [comment]
1. All of the above
2. That is possible yes
3. References can not have whitespace
4. Anything but newline, yeah
5. Yeah, any amount of whitespace
